server:
  port: 8084

spring:
  application:
    name: notification-service

  # Database configuration (H2 for demo)
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console (for development/demo)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging configuration
logging:
  level:
    com.example.notificationservice: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
